### ISSUE TITLE
A bug related with markedjs/marked on v24.2.4

### ISSUE THREAD

**Issue by enkhjile** [semantic-release/semantic-release#3725]
### Current behavior

I encountered with `markedjs` error after updating to `v24.2.4`. Rolling back to `v24.2.3` resolved the issue. I used `semantic-release` via `cycjimmy/semantic-release-action@v4` action.
```
[4:08:06 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[4:08:06 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[4:08:06 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[4:08:06 PM] [semantic-release] › ℹ  The next release version is 1.19.4-main.6
[4:08:06 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:08:06 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:08:06 PM] [semantic-release] › ⚠  Skip v1.19.4-main.6 tag creation in dry-run mode
[4:08:06 PM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/github" in dry-run mode
[4:08:06 PM] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/github" in dry-run mode
[4:08:06 PM] [semantic-release] › ✔  Published release 1.19.4-main.6 on main channel
[4:08:06 PM] [semantic-release] › ℹ  Release note for version 1.19.4-main.6:
[4:08:06 PM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: text.replace is not a function
```

### Expected behavior

Workflow should succeed without any errors and publish new release on GitHub.

### `semantic-release` version

v24.2.4

### CI environment

GitHub Actions

### Plugins used

- @semantic-release/commit-analyzer
- @semantic-release/release-notes-generator
- @semantic-release/github

### `semantic-release` configuration

```json
{
  "repositoryUrl": "https://github.com/gertech/okusuri-backend.git",
  "branches": [
    "release",
    {
      "name": "main",
      "prerelease": true
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github"
  ]
}
```

### CI logs

```
[4:08:06 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[4:08:06 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[4:08:06 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[4:08:06 PM] [semantic-release] › ℹ  The next release version is 1.19.4-main.6
[4:08:06 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:08:06 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:08:06 PM] [semantic-release] › ⚠  Skip v1.19.4-main.6 tag creation in dry-run mode
[4:08:06 PM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/github" in dry-run mode
[4:08:06 PM] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/github" in dry-run mode
[4:08:06 PM] [semantic-release] › ✔  Published release 1.19.4-main.6 on main channel
[4:08:06 PM] [semantic-release] › ℹ  Release note for version 1.19.4-main.6:
[4:08:06 PM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: text.replace is not a function
Please report this to https://github.com/markedjs/marked.
    at Renderer.insertEmojis [as emoji] (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/marked-terminal/index.js:474:15)
    at Renderer.transform (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/marked-terminal/index.js:529:24)
    at Renderer.heading (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/marked-terminal/index.js:96:15)
    at _Parser.parse (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/node_modules/marked/lib/marked.esm.js:2026:42)
    at parse (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/node_modules/marked/lib/marked.esm.js:1990:23)
    at Marked.parse (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/node_modules/marked/lib/marked.esm.js:2483:28)
    at Module.marked (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/node_modules/marked/lib/marked.esm.js:2517:27)
    at terminalOutput (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/index.js:34:17)
    at async run (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/index.js:227:28)
    at async Module.default (file:///Users/runner/runner-b/_work/_actions/cycjimmy/semantic-release-action/v4/node_modules/semantic-release/index.js:278:22)
Error: TypeError: text.replace is not a function
Please report this to https://github.com/markedjs/marked.
```

**Comment by glorat** [comment]
Just to confirm here too I faced the same issue and downgrading to v24.2.3 resolved it

**Comment by enkhjile** [comment]
@travi thanks. I'll try to mock this with direct semantic release. I opened this issue here because of the markjs major upgrades in the latest release

**Comment by enkhjile** [comment]
@travi, do you have any idea why this is happening? That way, I can potentially investigate and raise a PR.

**Comment by travi** [comment]
here is an example of a successful release with v24.2.4: https://github.com/form8ion/utils-cli/actions/runs/15091272705/job/42420131821#step:8:12

this suggests that the issue you are seeing is related to being executed in the context of the action since it works fine independently. we do not support the action or know much about it. if it can be shown that folks are seeing problems with this outside of the context of the action, but we simply dont have the bandwidth to investigate issues beyond our supported projects

for now, i'm going to close this issue, but we can reopen if it can be reproduced with a reduced reproduction.

**Comment by enkhjile** [comment]
> but we simply dont have the bandwidth to investigate issues beyond our supported projects

Yeah I completely get that. I'll investigate it further on the related action. Thanks again for your works 😊

**Comment by jacquesg** [comment]
This is an issue, as `semantic-release` and `marked-terminal` now use incompatible major versions of `marked`.

One way to address this, is to update `marked-terminal` to `7.3.0`, as it has:
```
  "peerDependencies": {
    "marked": ">=1 <16"
  },
```

See below for `pnpm`'s output for `semantic-release` `24.2.4`:

```
WARN  Issues with peer dependencies found                                                                                                                                                      
.                                                                                                                                                                                                                                                                                                                                          
└─┬ semantic-release 24.2.4                                                                                                                                                                     
  └─┬ marked-terminal 7.0.0                                                                                                                                                                     
    └── ✕ unmet peer marked@=13: found 15.0.1
```

```
pnpm why marked
Legend: production dependency, optional only, dev only

@asteriidae/github-action-release-info@0.0.1 /Users/jacquesg/dev/projects/asterias/github-action-release-info (PRIVATE)

dependencies:
semantic-release 24.2.4
├── marked 15.0.11
└─┬ marked-terminal 7.0.0
  └── marked 15.0.11 peer

devDependencies:
@asteriidae/semantic-release-config-npm 1.2.0
├─┬ @asteriidae/semantic-release-info 2.5.0 peer
│ └─┬ semantic-release 24.2.4 peer
│   ├── marked 15.0.11
│   └─┬ marked-terminal 7.0.0
│     └── marked 15.0.11 peer
├─┬ @semantic-release/changelog 6.0.3 peer
│ └─┬ semantic-release 24.2.4 peer
│   ├── marked 15.0.11
│   └─┬ marked-terminal 7.0.0
│     └── marked 15.0.11 peer
├─┬ @semantic-release/git 10.0.1 peer
│ └─┬ semantic-release 24.2.4 peer
│   ├── marked 15.0.11
│   └─┬ marked-terminal 7.0.0
│     └── marked 15.0.11 peer
└─┬ semantic-release 24.2.4 peer
  ├── marked 15.0.11
  └─┬ marked-terminal 7.0.0
    └── marked 15.0.11 peer
@asteriidae/semantic-release-info 2.5.0
└─┬ semantic-release 24.2.4 peer
  ├── marked 15.0.11
  └─┬ marked-terminal 7.0.0
    └── marked 15.0.11 peer
@semantic-release/changelog 6.0.3
└─┬ semantic-release 24.2.4 peer
  ├── marked 15.0.11
  └─┬ marked-terminal 7.0.0
    └── marked 15.0.11 peer
@semantic-release/git 10.0.1
└─┬ semantic-release 24.2.4 peer
  ├── marked 15.0.11
  └─┬ marked-terminal 7.0.0
    └── marked 15.0.11 peer
@semantic-release/release-notes-generator 14.0.3
└─┬ semantic-release 24.2.4 peer
  ├── marked 15.0.11
  └─┬ marked-terminal 7.0.0
    └── marked 15.0.11 peer
```

**Comment by travi** [comment]
> semantic-release 24.2.4
> ├── marked 15.0.11
> └─┬ marked-terminal 7.0.0
>   └── marked 15.0.11 peer

the reason `marked-terminal` is still at v7.0.0 in this context is not the fault of semantic-release. semantic-release supports ^7.0.0, but the context referenced above has grown stale and needs its own lockfile updated. that is why the peer dependency warning is highlighting the problem. 

the staleness could be dealt with without a change in semantic-release, but someone could send us a PR to raise the minimum of the range on the semantic-release side to force the package manager to resolve the compatible version

**Comment by jacquesg** [comment]
@travi Indeed, however, as it stands, the nett effect is doing a patch upgrade of `semantic-release` is probably going to result in a broken state. If `marked` was a non-peer dependency, this would probably not have been an issue, as `semantic-release` would have had its own version/copy.

Because its is a `peerDependency`, I believe it should play nicely with dependencies within its own tree. Put differently: `semantic-release` knows the versions of `marked` that are compatible with `marked-terminal` and should mirror those.

**Comment by jamesstanleystewart** [comment]
Saw the same using `cycjimmy/semantic-release-action@v4` github action

temporarily fixed with 
```
        with:
          semantic_version: v24.2.3
```
