### ISSUE TITLE
Plugins with array configuration not found when using `npx`

### ISSUE THREAD

**Issue by crash7** [semantic-release/semantic-release#999]
Hello!

## Current behavior

I'm using a shared configuration in an npm package that contains a plugin that is configured with the array form:
```
["@semantic-release/git", {
          "assets": ["package.json"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }]
```
And when I run everything with `npx`, it can't find the `@semantic-release/git` plugin:
```
[20:31:54] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Cannot find module '@semantic-release/git'
    at Function.Module._resolveFilename (module.js:547:15)
    at resolveFileName (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
```

Note: the same happens with the `exec` plugin, I guess that there is something strange in the way the modules are resolved (also, this is working fine with 15.9).

## Expected behavior

Release is generated successfully

## Environment

- **semantic-release** version: 15.12.1
- CI environment: CircleCI
- Plugins used:
    "@semantic-release/commit-analyzer": "6.1.0",
    "@semantic-release/git": "7.0.5",
    "@semantic-release/github": "5.2.5",
    "@semantic-release/npm": "5.1.1",
    "@semantic-release/release-notes-generator": "7.1.4"

- **semantic-release** configuration:
```
module.exports = {
  "branch": "master",
  "plugins": [
      ["@semantic-release/commit-analyzer", {
          "releaseRules": [
              { "type": "ci", "release": "patch" }
          ]
      }],
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      "@semantic-release/github",
      ["@semantic-release/git", {
          "assets": ["package.json"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }]
  ],
  "preset": "angular"
};
```
- CI logs:
```
npx: installed 1477 in 22.866s
[20:31:54] [semantic-release] › ℹ  Running semantic-release version 15.12.1
[20:31:54] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Cannot find module '@semantic-release/git'
    at Function.Module._resolveFilename (module.js:547:15)
    at resolveFileName (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:41)
    at loadPlugin (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/plugins/utils.js:49:82)
    at options.plugins.castArray.reduce (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/plugins/index.js:17:37)
    at Array.reduce (<anonymous>)
    at module.exports (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/get-config.js:75:35)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '@semantic-release/git'
    at Function.Module._resolveFilename (module.js:547:15)
    at resolveFileName (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:41)
    at loadPlugin (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/plugins/utils.js:49:82)
    at options.plugins.castArray.reduce (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/plugins/index.js:17:37)
    at Array.reduce (<anonymous>)
    at module.exports (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/circleci/.npm/_npx/103/lib/node_modules/semantic-release/lib/get-config.js:75:35)
    at <anonymous> code: 'MODULE_NOT_FOUND' }Exited with code 1
```

**Comment by pvdlg** [comment]
How is semantic-release installed? Globally or locally? Do you have the `semantic-release` devDependency in your `package.json`?

How is installed your shareable configuration? Do you have is as a devDependency in your `package.json`?

What is the content of your shareable config?

Can you provide a link to your repo?

**Comment by crash7** [comment]
Hi! Are you familiar with `npx`?
https://www.npmjs.com/package/npx - https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b

The command we use is:
```
npx -p semantic-release-apps-config -p semantic-release semantic-release -e semantic-release-apps-config
```

> How is semantic-release installed? Globally or locally? 

npx installes them locally in temporal folder to run the command.

> Do you have the semantic-release devDependency in your package.json?

No, that's the beauty of `npx`, I don't need to install them in the app itself.

> How is installed your shareable configuration? Do you have is as a devDependency in your package.json?

Same as before

> What is the content of your shareable config? I'm not sure if what you provided under "semantic-release configuration" is the config in your project or if it is the shareable config itself.

The shareable config it's the one I provided earlier, yes.

> What are the dependencies in the package.json of your shareable config?

The ones listed in the repo

> Can you provide a link to your repo?

It's a private one in our org, if this is necessary I can try to create a public one with a public shareable config package.

**Comment by pvdlg** [comment]
> Hi! Are you familiar with npx?
> npx installs them locally in temporal folder to run the command.
> No, that's the beauty of npx, I don't need to install them in the app itself.

Yes I am familiar with `npx` and no `npx` doesn't necessarily install package in a temp folder or execute them globally. If you define a dependency or devDependency in your `package.json` and run `npx` from there is will execute the locally installed package, therefore package resolution will be done from there.

Can you please confirm if you have either `semantic-release` or `semantic-release-apps-config` in `dependencies` or `devDependencies` in your project's `package.json`?

> The ones listed in the repo

Just to be sure, that means in your shareable config `semantic-release-apps-config` module you have a `package.json` and `@semantic-release/release-notes-generator`, `@semantic-release/npm`, `@semantic-release/github` and `@semantic-release/git` are defined as `dependencies` and not `devDependencies` there?

**Comment by crash7** [comment]
Neither `semantic-release` or `semantic-release-apps-config` are in the `package.json` of the main app repo. We use npx as a step in the CI and avoid adding the `release` config in all the repos (it makes everything more portable, specially when adding new projects to the release party).

Regarding the last part: Yes, this is the package.json of the shareable config module (`semantic-release-apps-config`):

```
  "dependencies": {
    "@semantic-release/commit-analyzer": "6.1.0",
    "@semantic-release/git": "7.0.5",
    "@semantic-release/github": "5.2.5",
    "@semantic-release/npm": "5.1.1",
    "@semantic-release/release-notes-generator": "7.1.4"
  },
  "peerDependencies": {
    "semantic-release": "15.12.1"
  }
```

**Comment by crash7** [comment]
@pvdlg just tested the new version and it works perfect. Kudos for fixing this so quickly!! Thank you so much 😄
