### ISSUE TITLE
TypeError: gitTags is not a function

### ISSUE THREAD

**Issue by Hyperkid123** [semantic-release/semantic-release#996]
## Current behavior

Failed to release new version after merging to master branch, when using 15.12.1 version. (Works with 15.12.0)

## Expected behavior

Release new package version after merge.

## Environment

- **semantic-release** version: 15.12.1
- CI environment: Travis
- Plugins used: 
  - @semantic-release/git": "^7.0.5
  - @semantic-release/npm": "^5.1.1
- **semantic-release** configuration:
```json
  "release": {
    "prepare": [
      "@semantic-release/npm",
      {
        "path": "@semantic-release/git",
        "assets": [
          "package.json"
        ],
        "message": "Release of new version: ${nextRelease.version} <no> [skip ci]"
      }
    ]
  }
```
- CI logs: https://travis-ci.org/Hyperkid123/data-driven-forms/builds/458694021#L857

**Comment by pvdlg** [comment]
I can't reproduce the issue. I'm very confused about what happen there...
The function `gitTags ` called [here](https://github.com/semantic-release/semantic-release/blob/c93775cc382ba1ba27a470333c561d27da45d322/lib/get-last-release.js#L33) does exists [there](https://github.com/semantic-release/semantic-release/blob/c93775cc382ba1ba27a470333c561d27da45d322/lib/git.js#L23). I don't know how could not find it...

Is it something systematic? Can you reproduce it?

**Comment by Hyperkid123** [comment]
@pvdlg i will try it again and let you know.

**Comment by pvdlg** [comment]
@Hyperkid123 did you had a change to test that again? I see you have successful build on your repo now: https://travis-ci.org/Hyperkid123/data-driven-forms/builds/459063120

**Comment by Hyperkid123** [comment]
@pvdlg no sorry i did not. I'm using older version (15.12.0).  I will go ahead and try it today.

**Comment by Hyperkid123** [comment]
@pvdlg so i've used the version 15.12.1 again and it again the travis build is failing. I tried it on a different repo with the same result: https://travis-ci.org/data-driven-forms/react-starter/builds/460661446#L650, with the same error (tried multiple configurations, with same results). 

The only "weird" thing i've noticed is that the version of the semantic on Travis release does not match the one specified in package.json

in travis
```
[08:48:22] [semantic-release] › ℹ  Running semantic-release version 15.12.0
``` 

in console on my PC
```
[10:26:06] [semantic-release] › ℹ  Running semantic-release version 15.12.2
```

in package JSON
```
"semantic-release": "^15.12.2",
```
https://github.com/data-driven-forms/react-starter/commit/a39fa38e5e175f621f2812116cfdf43e31f7bd79

When in run the release from terminal it will publish the new version without any issues.

Its a bit of a head scratcher... But since i am the only one with this issue, it is most likely something wrong on my side.

**Comment by pvdlg** [comment]
I think you have a corrupt cache on Travis. You should delete that cache and restart your build.

Also you should not cache `node_module` but `$HOME/.npm` instead: https://twitter.com/maybekatz/status/905213355748720640

**Comment by Hyperkid123** [comment]
@pvdlg Deleting cache helped (could have tried that first 🤦‍♂️ ). Thanks for the tips!
